### ISSUE TITLE
Travis integrálása a projektbe

### ISSUE THREAD

**Issue by bgyarm** [BME-MIT-IET/BBKM-iet-2018#1]
A Travis folytonos integrációs eszközt használva teszteljük a projektet!

**Comment by GribMate** [comment]
A funckiót a következő branch-ben próbáltam megvalósítani, azonban 14 commit alatt nem sikerült megfelelő konfigurációs beállításokat találnom.
Javaslom az AppVeyor-nál maradást és a többi feladatra fókuszálást.
[A branch](https://github.com/BME-MIT-IET/BBKM-iet-2018/commits/add-travis)
[Az issue wiki oldala](https://github.com/BME-MIT-IET/BBKM-iet-2018/wiki/Travis-integr%C3%A1l%C3%A1sa-a-projektbe-%231)

**Comment by GribMate** [comment]
#3 próba

**Comment by GribMate** [comment]
A Travis CI helyett a Visual Studio Team Services (VSTS) CI megoldását használva a folyamatos integrációs eszköz hozzáadásra került. A README.md is frissítést kapott ennek megfelelően.
A változtatáshoz nem tartozik külön branch, de kérem a megoldást review-ját és utána az issue ismét zárható.

**Comment by bgyarm** [comment]
A VSTS sikeresen build-elte a projektet, az integráció megfelelő.
