### ISSUE TITLE
Egységtesztek készítése/kiegészítése

### ISSUE THREAD

**Issue by Beni252** [BME-MIT-IET/BBKM-iet-2018#11]
A már meglévő teszteket ki kéne bővíteni, hiszen még nincs mindenre unit teszt, A következő metódusok unit tesztelését javaslom (mindegyik a dotNetRDF projekt Core mappájában található):
-A GraphFactory osztály TryGetGraph és Reset függvényét
-Az Extensions osztály CopyNode függvényét
-A NestedNameSpaceMapper DecrementNesting függvényét
-A ThreadSafeGraph GetNextBlankNodeId függvényét

**Comment by Beni252** [comment]
Elkészítettem az unit teszteket az unittests [branch](https://github.com/BME-MIT-IET/BBKM-iet-2018/tree/unittests)-ben. Valaki reviewezze és mergelje a masterrel. [Itt a pull request.](https://github.com/BME-MIT-IET/BBKM-iet-2018/pull/12)

**Comment by CocaCola97** [comment]
Mergeltem
