### ISSUE TITLE
JsonLdWriter.RdfToObject method doesn't always work for double values

### ISSUE THREAD

**Issue by CocaCola97** [BME-MIT-IET/BBKM-iet-2018#14]
JsonLdWriter.RdfToObject method doesn't work for double values when the default decimal separator is not "."

**Comment by CocaCola97** [comment]
Issue fixed, [pull request](https://github.com/BME-MIT-IET/BBKM-iet-2018/pull/15)

**Comment by GribMate** [comment]
Átvizsgálva, merge-lve.
