### ISSUE TITLE
NTriplesFormatter tests

### ISSUE THREAD

**Issue by CocaCola97** [BME-MIT-IET/BBKM-iet-2018#16]
Az NTriplesFormatter osztály funkcionalitásának nagyrésze teszteletlen, ezért írni kellene új teszteket.

**Comment by CocaCola97** [comment]
Két új tesztet hozzáadtam. [Pull request](https://github.com/BME-MIT-IET/BBKM-iet-2018/pull/17)

**Comment by GribMate** [comment]
Átvizsgálva és merge-elve.
