### ISSUE TITLE
Metódus refaktorálása

### ISSUE THREAD

**Issue by bgyarm** [BME-MIT-IET/BBKM-iet-2018#6]
A Core mappában lévő EqualityHelper.cs osztályban egy függvénynek nagyobb mértékű a kognitív bonyolultsága mint a javasolt 15.
Ajánlom a függvény szétbontását két külön egységre.
Metódus (101. sor):
public static bool AreLiteralsEqual(ILiteralNode a, ILiteralNode b);
Analízis eszköz üzenete:
Refactor this method to reduce its Cognitive Complexity from 18 to the 15 allowed.

**Comment by CocaCola97** [comment]
Refactored method AreLiteralsEqual in EqualityHelper.cs, making it simpler and easier to read. [Pull Request](https://github.com/BME-MIT-IET/BBKM-iet-2018/pull/7)
