### ISSUE TITLE
Kódlefedettség vizsgálata

### ISSUE THREAD

**Issue by GribMate** [BME-MIT-IET/BBKM-iet-2018#8]
Codecov.io integrálásával szükséges vizsgálni a tesztek kódlefedettségét.

**Comment by GribMate** [comment]
Az integráció sikerült, az eredmények a következő oldalon láthatók a legutolsó commit-ról: [Codecov.io report](https://codecov.io/gh/BME-MIT-IET/BBKM-iet-2018).
[A branch.](https://github.com/BME-MIT-IET/BBKM-iet-2018/tree/codecov-added)
[A wiki oldal.](https://github.com/BME-MIT-IET/BBKM-iet-2018/wiki/%233-K%C3%B3dlefedetts%C3%A9g-vizsg%C3%A1lata)
#9 pull request az ág beolvasztására.
Ennek alapján bővíthetők az egységtesztek a továbbiakban.
Kérem a review-t és az issue zárható.

**Comment by bgyarm** [comment]
Report elkészült, az ág master branch-el való merge-elése megtörtént.
